services:
  - type: web
    plan: free
    runtime: image
    name: n8n-service
    image:
      url: docker.io/n8nio/n8n:latest
    envVars:
      # Wymagane - klucz szyfrujący dane
      - key: N8N_ENCRYPTION_KEY
        generateValue: true

      # Nie ustawiamy zmiennych DB_ – używany będzie lokalny SQLite
      # Dodaj podstawowe zabezpieczenie logowania
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "admin"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "superhaslo"

      # Można ustawić strefę czasową
      - key: GENERIC_TIMEZONE
        value: Europe/Warsaw

      # Zapisz dane wewnątrz kontenera (niestabilne, ale działa)
      - key: DB_TYPE
        value: sqlite

      # Katalog do przechowywania danych SQLite
      - key: DB_SQLITE_DATABASE
        value: /data/database.sqlite
